### ISSUE TITLE
Where is thanos builder code?

### ISSUE THREAD

**Issue by glazedtorus** [petikvx/MSIL-Ransom#6]
Do you have the decompiled version or original version? The zip files online are password protected.

**Comment by petikvx** [comment]
Do you have any sha256sum or another sample example ?

**Comment by petikvx** [comment]
https://www.recordedfuture.com/thanos-ransomware-builder
https://beta.virusbay.io/question/browse/60d546b834f9560017412002
https://anonfiles.com/36L6W026ue/Thanos-Ransomware-Private_Builder_Decrypter_zip

**Comment by petikvx** [comment]
Found it, I will commit under 24h

**Comment by petikvx** [comment]
`File moved : /home/petik/thanos/Thanos Ransomware Decrypter.exe Constructor.Win32.Agent.apy-b218562b19614c2857cbc4f46816702d1c7d5c06a4b8d572a6a2a626fdba3e87
File moved : /home/petik/thanos/Thanos Ransomware Builder.exe Constructor.Win32.Ransom.a-b94c888786bd50610331593396e80c1777ce0c54bb2f049338e31f98c2a61215
`

**Comment by petikvx** [comment]
`Thanos Ransomware Builder.exe:   PE32 executable (GUI) Intel 80386, for MS Windows
Thanos Ransomware Decrypter.exe: PE32 executable (GUI) Intel 80386, for MS Windows
`

It's not a MSIL exe. I cannot decompile them. So sorry.

**Comment by petikvx** [comment]
you can download it here : https://app.any.run/tasks/25ce8394-a324-41bf-82d9-d5ee8adbf64b/
